---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: buildah-pipeline
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 300Mi
  params:
  - name: source-repo
    value: https://github.com/cloud-native-garage-method-cohort/tobias-kaatz-buildah.git
  - name: image-repo
    value: quay.io/tkaatz/buildah-assignment