---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger-b
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: buildah-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: buildah-pipeline
        params:
          - name: app-name
            value: tobias-kaatz-buildah-app
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/tobias-kaatz-buildah.git
          - name: image-repo
            value: quay.io/tkaatz/buildah-assignment
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 300Mi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger-b
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger-b
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: vcs-trigger-b
      template:
        name: vcs-trigger-b
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vcs-trigger-b
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-vcs-trigger-b
    weight: 100
